---
name: 
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: icepuma/rust-action@master
        with:
          args: cargo fmt -- --check && cargo clippy -- -W clippy::pedantic -Dwarnings && cargo test
